"""version 1

Revision ID: 3e6a7cdaf808
Revises: 621f2c8dda8f
Create Date: 2026-06-26 13:02:28.941860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3e6a7cdaf808"
down_revision: Union[str, Sequence[str], None] = "621f2c8dda8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("author_code", sa.String(length=6), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_authors_author_code_active",
        "authors",
        ["author_code"],
        unique=True,
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.create_table(
        "courses",
        sa.Column("reestr_number", sa.String(length=4), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_courses_reestr_number_active",
        "courses",
        ["reestr_number"],
        unique=True,
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.create_table(
        "persons",
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "students",
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("record_book_number", sa.String(length=8), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_students_record_book_number_active",
        "students",
        ["record_book_number"],
        unique=True,
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.create_table(
        "books",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("book_code", sa.String(length=6), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_books_book_code_active",
        "books",
        ["book_code"],
        unique=True,
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.create_table(
        "passports",
        sa.Column("number", sa.String(length=10), nullable=False),
        sa.Column("registrated_in", sa.String(length=200), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="False", nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["persons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_passports_number_active",
        "passports",
        ["number"],
        unique=True,
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.create_index(
        "uq_passports_person_id_active",
        "passports",
        ["person_id"],
        unique=True,
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.create_table(
        "students_courses",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("student_id", "course_id"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.drop_table("students_courses")
    op.drop_index(
        "uq_passports_person_id_active",
        table_name="passports",
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.drop_index(
        "uq_passports_number_active",
        table_name="passports",
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.drop_table("passports")
    op.drop_index(
        "uq_books_book_code_active",
        table_name="books",
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.drop_table("books")
    op.drop_index(
        "uq_students_record_book_number_active",
        table_name="students",
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.drop_table("students")
    op.drop_table("persons")
    op.drop_index(
        "uq_courses_reestr_number_active",
        table_name="courses",
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.drop_table("courses")
    op.drop_index(
        "uq_authors_author_code_active",
        table_name="authors",
        postgresql_where=sa.text("is_deleted = False"),
    )
    op.drop_table("authors")
    # ### end Alembic commands ###
